// You must replace this URL with the Web App URL generated by Google Apps Script
const API_URL = "https://script.google.com/macros/s/AKfycbzwFVl-W2I1lPbVhvyXPLKDY9xab0XaKHKKdiJbI-iVjFe8qcMF5j0YrUD1idIQu8A/exec";

async function loadData() {
  const container = document.getElementById('projects-container');
  try {
    const response = await fetch(API_URL);
    if (!response.ok) throw new Error("Network response was not ok");
    const data = await response.json();
    renderProjects(data);
  } catch (error) {
    console.error("Error loading data:", error);
    container.innerHTML = '<p style="text-align: center; color: var(--muted); padding: 2rem;">Error loading projects from database. Please ensure the Google Apps Script URL is correct and deployed.</p>';
  }
}

function renderProjects(data) {
  const container = document.getElementById('projects-container');
  container.innerHTML = ''; // Clear loading message
  
  const projects = data.projects;
  const tasks = data.tasks;
  const artists = data.artists;
  const appointments = data.appointments;
  
  const runes = ['ᛟ', 'ᚠ', 'ᛒ', 'ᚨ', 'ᛏ', 'ᛗ', 'ᛚ'];

  projects.forEach((proj, index) => {
    // Skip empty rows
    if (!proj.Name) return;

    // Filter related data based on the Project Name matching column A
    const projTasks = tasks ? tasks.filter(t => t.Project === proj.Name) : [];
    const projArtists = artists ? artists.filter(a => a.Project === proj.Name) : [];
    const projAppts = appointments ? appointments.filter(a => a.Project === proj.Name) : [];

    const article = document.createElement('article');
    article.className = 'project-card';
    
    // Header
    const projectNameHtml = (proj.Link && proj.Link !== 'NA' && proj.Link.trim() !== '')
      ? `<a href="${proj.Link}" target="_blank" style="text-decoration: underline; text-underline-offset: 4px; color: inherit;">${proj.Name}</a>`
      : proj.Name;
      
    let headerHtml = `
      <header class="project-header">
        <div class="project-meta-line">
          <span class="project-date-range">${(() => {
            const runTimeKey = Object.keys(proj).find(k => k.toLowerCase().includes('run time'));
            return (runTimeKey && proj[runTimeKey] && proj[runTimeKey] !== 'NA') ? proj[runTimeKey] : 'TBD';
          })()}</span>
          <span class="project-rune" aria-hidden="true">${runes[index % runes.length]}</span>
        </div>
        <h3 class="project-name">${projectNameHtml}</h3>
        <p class="project-summary">${proj.Description || ''}</p>
      </header>
    `;

    // Tasks (Dropdown)
    let tasksHtml = '';
    if (projTasks.length > 0) {
      const taskRows = projTasks.map(t => {
        let statusClass = 'badge--pending';
        let statusText = t.Status || 'Pending';
        if (statusText.toLowerCase().includes('progress')) statusClass = 'badge--inprogress';
        if (statusText.toLowerCase().includes('done')) statusClass = 'badge--done';
        
        let noteHtml = (t.Note && t.Note !== 'NA' && t.Note.trim() !== '') ? `<div style="color: var(--muted); font-size: 0.75rem; margin-top: 0.3rem;">Note: ${t.Note}</div>` : '';
        
        return `
          <tr>
            <td>
              <div style="font-weight: 500;">${t.Task || ''}</div>
              ${noteHtml}
            </td>
            <td><span class="badge ${statusClass}">${statusText}</span></td>
            <td>${t.Responsible || '—'}</td>
          </tr>
        `;
      }).join('');
      
      tasksHtml = `
        <details class="task-board">
          <summary class="board-title">
            Task Board
            <svg class="dropdown-arrow" viewBox="0 0 24 24" width="16" height="16" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>
          </summary>
          <table class="task-table" aria-label="Task Board for ${proj.Name}">
            <thead>
              <tr>
                <th>Task</th>
                <th>Status</th>
                <th>Assigned To</th>
              </tr>
            </thead>
            <tbody>
              ${taskRows}
            </tbody>
          </table>
        </details>
      `;
    }

    // Artists (Dropdown)
    let artistsHtml = '';
    if (projArtists.length > 0) {
      const artistRows = projArtists.map(a => {
        let nameHtml = a['Artist Name'] || 'Unknown';
        if (a.Link && a.Link !== 'NA' && a.Link.trim() !== '') {
          nameHtml = `<a href="${a.Link}" target="_blank" style="text-decoration: underline; text-underline-offset: 3px; color: inherit;">${nameHtml}</a>`;
        }
        return `
          <li>${nameHtml} <span>(${a['Art Type'] || 'Artist'})</span></li>
        `;
      }).join('');
      
      artistsHtml = `
        <details class="task-board">
          <summary class="board-title">
            Involved Artists
            <svg class="dropdown-arrow" viewBox="0 0 24 24" width="16" height="16" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>
          </summary>
          <ul class="artists-list">
            ${artistRows}
          </ul>
        </details>
      `;
    }

    // Appointments (Calendar Widget)
    let apptsHtml = '';
    if (projAppts.length > 0) {
      const apptRows = projAppts.map(a => {
        let day = "??";
        let month = "MMM";
        
        if (a.Date) {
           let dateStr = String(a.Date).trim();
           // Check if it matches dd.mm.yy format
           const parts = dateStr.split('.');
           if (parts.length >= 2) {
             day = parts[0].padStart(2, '0');
             const m = parseInt(parts[1], 10);
             const months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
             if (m >= 1 && m <= 12) {
               month = months[m - 1];
             }
           } else {
             // Fallback
             day = dateStr.substring(0, 2);
           }
        }
        
        // Also check if time column has a different header (like Time (military...))
        const timeKey = Object.keys(a).find(k => k.toLowerCase().includes('time'));
        const timeVal = timeKey ? a[timeKey] : a.Time;
        const timeStr = (timeVal && timeVal !== 'NA') ? `🕒 ${timeVal} &nbsp;•&nbsp; ` : '';
        const locStr = a.Location ? `📍 ${a.Location}` : '';
        
        let calUrl = '#';
        let title = a['Meeting Name'] || 'Appointment';
        let textDetails = a.Description || '';
        let location = a.Location || '';
        
        // Basic Google Calendar Template
        calUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(title)}&details=${encodeURIComponent(textDetails)}&location=${encodeURIComponent(location)}`;
        
        // Try parsing dates for calendar (YYYYMMDDTHHmmss)
        if (a.Date && String(a.Date).includes('.')) {
          let dp = String(a.Date).trim().split('.');
          if (dp.length >= 2) {
             let y = dp[2] ? dp[2].trim() : '26'; // Default to 2026 based on sheet
             if (y.length === 2) y = '20' + y;
             let m = dp[1].padStart(2, '0');
             let d = dp[0].padStart(2, '0');
             let baseDate = `${y}${m}${d}`;
             
             let startT = '000000';
             let endT = '000000';
             let isAllDay = true;
             
             if (timeVal && timeVal !== 'NA') {
               let times = String(timeVal).match(/(\d{1,2})[^\d](\d{2})/g);
               if (times && times.length > 0) {
                 isAllDay = false;
                 startT = times[0].replace(/[^\d]/g, '').padStart(4, '0') + '00';
                 if (times.length > 1) {
                   endT = times[1].replace(/[^\d]/g, '').padStart(4, '0') + '00';
                 } else {
                   let startH = parseInt(startT.substring(0,2));
                   endT = String(startH + 1).padStart(2, '0') + startT.substring(2);
                 }
               }
             }
             
             if (isAllDay) {
               calUrl += `&dates=${baseDate}/${baseDate}`;
             } else {
               calUrl += `&dates=${baseDate}T${startT}/${baseDate}T${endT}`;
             }
          }
        }
        
        return `
            <li class="appointment-item">
              <div class="appointment-date">
                <span class="appt-day">${day}</span>
                <span class="appt-month">${month}</span>
              </div>
              <div class="appointment-info">
                <p class="appt-name">${title}</p>
                <p class="appt-location">${timeStr}${locStr}</p>
                <p class="appt-desc">${a.Description || ''}</p>
              </div>
              <a href="${calUrl}" target="_blank" class="add-to-cal" aria-label="Add to Calendar">+ Add to Calendar</a>
            </li>
        `;
      }).join('');
      
      apptsHtml = `
        <div class="calendar-widget">
          <h4 class="board-title">Upcoming Appointments</h4>
          <ul class="appointment-list">
            ${apptRows}
          </ul>
        </div>
      `;
    }

    article.innerHTML = headerHtml + apptsHtml + tasksHtml + artistsHtml;
    container.appendChild(article);
    
    // Add rune separator if not the last item
    if (index < projects.length - 1) {
      const sep = document.createElement('div');
      sep.className = 'card-rune-sep';
      sep.setAttribute('aria-hidden', 'true');
      sep.innerText = 'ᚷ ᛇ ᚦ';
      container.appendChild(sep);
    }
  });
}

document.addEventListener('DOMContentLoaded', loadData);
